#ifndef CONTACORRENTE_GLOBAL_H
#define CONTACORRENTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTACORRENTE_LIBRARY)
#  define CONTACORRENTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTACORRENTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTACORRENTE_GLOBAL_H
